version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - app-network
    command: redis-server --appendonly yes

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-api
    ports:
      - '5000:5000'
    depends_on:
      - redis
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
